### ISSUE TITLE
Application error: a client-side exception has occurred (next@13.4.0)

### ISSUE THREAD

**Issue by kang-theo** [kang-theo/next.js-website#4]
```bash
Application error: a client-side exception has occurred (see the browser console for more information).
```

```bash
69-73c02bf95a71affb.js:1  TypeError: Failed to construct 'URL': Invalid URL
    at Object.prefetch (69-73c02bf95a71affb.js:1:12172)
    at b (250-2e457fc60adb22b3.js:1:1501)
    at 250-2e457fc60adb22b3.js:1:2616
    at aI (fd9d1056-14b12944d2fc124c.js:1:72882)
    at a3 (fd9d1056-14b12944d2fc124c.js:1:84323)
    at a5 (fd9d1056-14b12944d2fc124c.js:1:84961)
    at a8 (fd9d1056-14b12944d2fc124c.js:1:84845)
    at a5 (fd9d1056-14b12944d2fc124c.js:1:85906)
    at a8 (fd9d1056-14b12944d2fc124c.js:1:84845)
    at a5 (fd9d1056-14b12944d2fc124c.js:1:85906)	
window.console.error
```

**Comment by kang-theo** [comment]
<Link className="text-white/90 hover:text-white" href="https://github.com/#">
